# Generated by Django 4.2.15 on 2024-10-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='landlord_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
