# Generated by Django 4.2.15 on 2024-10-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0003_profile_landlord_email_property_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='landlord_email',
        ),
        migrations.AddField(
            model_name='property',
            name='landlord_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
