# Generated by Django 4.2.15 on 2024-10-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0005_alter_property_status_propertyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
