# Generated by Django 5.1.1 on 2024-10-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0007_remove_property_image_alter_property_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
