# Generated by Django 4.2.15 on 2024-10-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0008_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='vacant', max_length=50),
        ),
    ]
