# Generated by Django 5.1.1 on 2024-10-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0009_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], max_length=50),
        ),
    ]
