# Generated by Django 4.2.16 on 2024-11-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0010_alter_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location_longitude',
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=50),
        ),
    ]
